version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn commitlint-circle

      - run: yarn test:lint

workflows:
  version: 2

  test:
    jobs:
      - lint
